language: node_js
jobs:
  include:
    - stage: test
      script:
        - npm run cover
      node_js:
        - 14.15.0
        - -12
        - -13
        - -14
        - -15
    - stage: doc
      node_js: lts/*
      skip_cleanup: '--delete--'
      script:
        - npm run lint
        - npm run docs
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: '--delete--'
        cleanup: 'false'
        script: npx semantic-release
branches:
  only:
    - master
    - /^mkpr/.*$/
    - /^npm-template-sync/.*$/
